#! /usr/bin/env bash
set -e

# dependencies
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y postgresql-12 golang 
apt-get clean

echo "\nDone installing dependencies...\n"


# apt-get install -y curl wget git apt-transport-https \
#                    libpq-dev libsqlite3-dev libsasl2-dev \
#                    postgresql-client postgresql postgresql-contrib \
#                    sudo vim zlib1g-dev supervisor psmisc \
#                    jq netcat golang # Parsing stellar-core JSON for standalone network and checking core HTTP server
